// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import ()

type Notification struct {
	ID        int32
	TeacherID int32
	Content   string
}

type Registration struct {
	ID        int32
	StudentID int32
	TeacherID int32
}

type Student struct {
	ID          int32
	Name        string
	Email       string
	IsSuspended bool
}

type Teacher struct {
	ID    int32
	Name  string
	Email string
}
