// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: notifications.sql

package sqlc

import (
	"context"
)

const createNotification = `-- name: CreateNotification :one
insert into notifications
(teacher_id, content)
values
    ($1, $2)
returning id, teacher_id, content
`

type CreateNotificationParams struct {
	TeacherID int32
	Content   string
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification, arg.TeacherID, arg.Content)
	var i Notification
	err := row.Scan(&i.ID, &i.TeacherID, &i.Content)
	return i, err
}
